// GENERATED by `npm run bundle-skills` — do not edit here.
// Edit the source under apps/agentops/src/ and re-run bundle-skills; `--check` verifies these stay in sync.

/**
 * The single home for the authored requirement-contract document's filename — where a
 * feature dir's human-authored WHAT lives (DOC_LIFECYCLE: a signed requirements DELTA,
 * not a current-state specification — the very confusion the 2026-07-09 rename closes).
 *
 * New dirs (docs/requirements/<slug>/, spawned by planning-tree) use `requirements.md`.
 * Legacy signed dirs (docs/specs/<slug>/) keep `spec.md` FOREVER: a signature pins the
 * committed path + blob (ApprovedSpecRef), so renaming history would break every signed
 * ref. Every reader resolves through here; no consumer spells the filename twice.
 *
 * Dependency-free leaf (node builtins only) so bundle-skills can vendor a faithful copy
 * into the self-contained skills (to-spec / to-detail-design).
 */

import fs from 'node:fs';
import path from 'node:path';

/** The authored document in dirs created from 2026-07-09 on. */
export const REQUIREMENTS_DOC = 'requirements.md';

/** The legacy filename in already-signed dirs (kept: signatures pin path + blob). */
export const LEGACY_SPEC_DOC = 'spec.md';

/**
 * The requirement document inside `dirAbs`: `requirements.md` when present, else the
 * legacy `spec.md` (returned as the target path even when neither exists yet — new
 * writes go to the new name).
 */
export function requirementsDocPath(dirAbs: string): string {
  const modern = path.join(dirAbs, REQUIREMENTS_DOC);
  if (fs.existsSync(modern)) return modern;
  const legacy = path.join(dirAbs, LEGACY_SPEC_DOC);
  if (fs.existsSync(legacy)) return legacy;
  return modern;
}
