#!/usr/bin/env tsx
/**
 * Vendor the single-source deterministic libs into each self-contained skill.
 *
 * The one implementation of each lib lives under src/. This copies it (with a GENERATED
 * header) into each skill so the skill directory is self-contained and imports nothing
 * from outside itself at runtime. Other in-repo callers import the source directly; the
 * skills import their vendored copy. Each source must be a dependency-free leaf (no
 * imports) so a plain copy is a faithful, deterministic vendor. Re-run after editing a
 * source.
 *
 *   npm run bundle-skills            # write the vendored copies
 *   npm run bundle-skills -- --check # verify the copies are up to date (CI), exit 1 if stale
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { agentopsPackagePath, repositoryPath } from '../src/runtime/roots.js';

const HEADER =
  '// GENERATED by `npm run bundle-skills` — do not edit here.\n' +
  '// Edit the source under apps/agentops/src/ and re-run bundle-skills; `--check` verifies these stay in sync.\n\n';

interface Job {
  source: string;
  targets: string[];
}

const JOBS: Job[] = [
  {
    source: 'src/design/lint.ts',
    targets: [
      '.claude/skills/to-system-design/scripts/lib/design-lint.ts',
      '.claude/skills/to-detail-design/scripts/lib/design-lint.ts',
    ],
  },
  {
    source: 'src/authoring/lint.ts',
    targets: ['.claude/skills/to-spec/scripts/lib/authoring-lint.ts'],
  },
  {
    source: 'src/authoring/spec-doc.ts',
    targets: [
      '.claude/skills/to-spec/scripts/lib/spec-doc.ts',
      '.claude/skills/to-detail-design/scripts/lib/spec-doc.ts',
    ],
  },
];

const check = process.argv.includes('--check');
let stale = 0;

for (const job of JOBS) {
  const expected = HEADER + readFileSync(agentopsPackagePath(job.source), 'utf8');
  for (const rel of job.targets) {
    const path = repositoryPath(rel);
    if (check) {
      const current = existsSync(path) ? readFileSync(path, 'utf8') : '';
      if (current !== expected) {
        console.error(`stale vendored copy: ${rel}`);
        stale++;
      }
    } else {
      mkdirSync(dirname(path), { recursive: true });
      writeFileSync(path, expected);
      console.log(`vendored -> ${rel}`);
    }
  }
}

if (check) {
  if (stale) {
    console.error(`bundle-skills --check: ${stale} stale copy(ies). Run: npm run bundle-skills`);
    process.exit(1);
  }
  console.log('bundle-skills --check: all vendored copies up to date');
}
