// Command syncschemas refreshes the Designflow schemas embedded by the Go
// control plane from their canonical, language-neutral contract directory.
package main

import (
	"crypto/sha256"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/mrbaron3/servo/apps/control-plane/internal/reporoot"
)

func main() {
	if err := run(); err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "sync Designflow schemas: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	root, err := reporoot.Find(".")
	if err != nil {
		return err
	}
	canonicalRoot := filepath.Join(
		root,
		"contracts",
		"designflow",
		"contract-v1.0.0-rc.1",
		"contracts",
		"v1",
	)
	mirrorRoot := filepath.Join(
		root,
		"apps",
		"control-plane",
		"internal",
		"designgate",
		"schemas",
	)
	canonicalPaths, err := filepath.Glob(filepath.Join(canonicalRoot, "*.schema.json"))
	if err != nil {
		return err
	}
	if len(canonicalPaths) == 0 {
		return fmt.Errorf("canonical schema set in %s is empty", canonicalRoot)
	}
	canonicalNames := make(map[string]struct{}, len(canonicalPaths))
	for _, schemaPath := range canonicalPaths {
		canonicalNames[filepath.Base(schemaPath)] = struct{}{}
	}
	mirrorPaths, err := filepath.Glob(filepath.Join(mirrorRoot, "*.schema.json"))
	if err != nil {
		return err
	}
	var stale []string
	for _, schemaPath := range mirrorPaths {
		name := filepath.Base(schemaPath)
		if _, ok := canonicalNames[name]; !ok {
			stale = append(stale, name)
		}
	}
	if len(stale) > 0 {
		sort.Strings(stale)
		return fmt.Errorf("remove stale embedded schemas: %v", stale)
	}
	if err := os.MkdirAll(mirrorRoot, 0o755); err != nil {
		return err
	}
	digests := make(map[string]string, len(canonicalPaths))
	for _, sourcePath := range canonicalPaths {
		body, readErr := os.ReadFile(sourcePath)
		if readErr != nil {
			return readErr
		}
		if writeErr := os.WriteFile(
			filepath.Join(mirrorRoot, filepath.Base(sourcePath)),
			body,
			0o644,
		); writeErr != nil {
			return writeErr
		}
		digest := sha256.Sum256(body)
		digests[filepath.Base(sourcePath)] = fmt.Sprintf("%x", digest)
	}
	return writeDigestSource(root, digests)
}

func writeDigestSource(root string, digests map[string]string) error {
	names := make([]string, 0, len(digests))
	for name := range digests {
		names = append(names, name)
	}
	sort.Strings(names)
	var source strings.Builder
	source.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	source.WriteString("package designgate\n\n")
	source.WriteString("var pinnedSchemaSHA256 = map[string]string{\n")
	for _, name := range names {
		_, _ = fmt.Fprintf(&source, "\t%q: %q,\n", name, digests[name])
	}
	source.WriteString("}\n")
	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return fmt.Errorf("format generated schema digests: %w", err)
	}
	target := filepath.Join(
		root,
		"apps",
		"control-plane",
		"internal",
		"designgate",
		"schema_digests_generated.go",
	)
	if err := os.WriteFile(target, formatted, 0o644); err != nil {
		return fmt.Errorf("write generated schema digests: %w", err)
	}
	return nil
}
