#!/usr/bin/env tsx
/**
 * Vendor the single-source design lint into each self-contained skill.
 *
 * The one implementation lives at src/design/lint.ts. This copies it (with a GENERATED
 * header) into each skill so the skill directory is self-contained and imports nothing
 * from outside itself at runtime. Other in-repo callers import the source directly; the
 * skills import their vendored copy. Re-run after editing the source.
 *
 *   npm run bundle-skills            # write the vendored copies
 *   npm run bundle-skills -- --check # verify the copies are up to date (CI), exit 1 if stale
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const ROOT = process.cwd();
const SOURCE = resolve(ROOT, 'src/design/lint.ts');
const TARGETS = [
  '.claude/skills/to-basic-design/scripts/lib/design-lint.ts',
  '.claude/skills/to-db-design/scripts/lib/design-lint.ts',
  '.claude/skills/to-detail-design/scripts/lib/design-lint.ts',
];
const HEADER =
  '// GENERATED by `npm run bundle-skills` from src/design/lint.ts — do not edit here.\n' +
  '// Edit the source and re-run bundle-skills; `--check` verifies these stay in sync.\n\n';

const expected = HEADER + readFileSync(SOURCE, 'utf8');
const check = process.argv.includes('--check');

let stale = 0;
for (const rel of TARGETS) {
  const path = resolve(ROOT, rel);
  if (check) {
    const current = existsSync(path) ? readFileSync(path, 'utf8') : '';
    if (current !== expected) {
      console.error(`stale vendored copy: ${rel}`);
      stale++;
    }
  } else {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, expected);
    console.log(`vendored -> ${rel}`);
  }
}

if (check) {
  if (stale) {
    console.error(`bundle-skills --check: ${stale} stale copy(ies). Run: npm run bundle-skills`);
    process.exit(1);
  }
  console.log('bundle-skills --check: all vendored copies up to date');
}
